version: 1.2
workflows:
  -  name: foobar
     subclass: wdl
     authors:
       - name: Denis Yuen
         orcid: 0000-0002-6130-1021
       - name: UCSC Genomics Institute
         role: Institute
         affiliation: UCSC
     publish: true
     primaryDescriptorPath: /Dockstore2.wdl
     testParameterFiles:
       - /dockstore.wdl.json
     filters:
       branches:
         - develop
       tags:
         - gwas*
  -  name: foobar2
     subclass: cwl
     publish: no
     primaryDescriptorPath: /Dockstore.cwl
     readMePath: /foobar2/readme.md
     testParameterFiles:
       - /dockstore.cwl.json
  -  subclass: CWL
     name: bloop
     primaryDescriptorPath: /Dockstore.cwl
     readMePath: /other-readme.md
     testParameterFiles:
       - /dockstore.cwl.json
